BackEndProject/Models/Slider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Models
{
    public class Slider : BaseEntity 
    {
        public string Image { get; set; }
        public string Selling { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        [NotMapped]
        [Required(ErrorMessage ="Can't be empty")]
        public IFormFile Photo { get; set; }
    }
}

BackEndProject/Areas/AdminArea/Controllers/SliderController.cs
using BackEndProject.Data;
using BackEndProject.Helper;
using BackEndProject.Models;
using BackEndProject.ViewModels.SliderViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders = await _context.Sliders.ToListAsync();
            return View(sliders);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SliderCreateVM sliderCreate)
        {
            if (!ModelState.IsValid) return View();

            foreach (var photo in sliderCreate.Photos)
            {
                if (!photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photos", "Please choose correct image type");
                    return View();
                }


                if (!photo.CheckFileSize(200))
                {
                    ModelState.AddModelError("Photos", "Please choose correct image size");
                    return View();
                }
            }

            foreach (var photo in sliderCreate.Photos)
            {
                string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;

                string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", fileName);

                await BackEndProject.Helper.Helper.SaveFile(path, photo);

                Slider newSlider = new Slider
                {
                    Image = fileName,
                    Selling = sliderCreate.Sale,
                    Title = sliderCreate.Title,
                    Desc = sliderCreate.Desc,
                };

                await _context.Sliders.AddAsync(newSlider);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (id is null) return BadRequest();

            Slider slider = await GetByIdAsync(id);

            if (slider == null) return NotFound();

            SliderUpdateVM model = new SliderUpdateVM
            {
                Id = slider.Id,
                Sale = slider.Selling,
                Desc = slider.Desc,
                Title = slider.Title,
            };

            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, SliderUpdateVM sliderUpdate)
        {
            if (id is null) return BadRequest();

            if (!ModelState.IsValid) return View(sliderUpdate);

            var dbSlider = await GetByIdAsync((int)id);

            if (dbSlider == null) return NotFound();

            if (sliderUpdate.Photos != null)
            {

                foreach (var photo in sliderUpdate.Photos)
                {
                    if (!photo.CheckFileType("image/"))
                    {
                        ModelState.AddModelError("Photos", "Please choose correct image type");
                        return View(sliderUpdate);
                    }


                    if (!photo.CheckFileSize(500))
                    {
                        ModelState.AddModelError("Photos", "Please choose correct image size");
                        return View(sliderUpdate);
                    }

                }

                foreach (var item in sliderUpdate.Photos)
                {
                    string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", dbSlider.Image);
                    BackEndProject.Helper.Helper.DeleteFile(path);
                }

                foreach (var photo in sliderUpdate.Photos)
                {

                    string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;

                    string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", fileName);

                    await BackEndProject.Helper.Helper.SaveFile(path, photo);

                    dbSlider.Image = fileName;

                }



            }

            dbSlider.Selling = sliderUpdate.Sale;
            dbSlider.Title = sliderUpdate.Title;
            dbSlider.Desc = sliderUpdate.Desc;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int id)
        {
            Slider slider = await GetByIdAsync(id);

            if (slider == null) return NotFound();

            string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", slider.Image);

            //if (System.IO.File.Exists(path))
            //{
            //    System.IO.File.Delete(path);
            //}

            BackEndProject.Helper.Helper.DeleteFile(path);

            _context.Sliders.Remove(slider);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        private async Task<Slider> GetByIdAsync(int? id)
        {
            return await _context.Sliders
                                  .Where(m => m.Id == id)
                                  .FirstOrDefaultAsync();
        }
    }

}

BackEndProject/Areas/AdminArea/Views/Slider/Create.cshtml
@model SliderCreateVM

@{
    ViewData["Title"] = "Create";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <h3>Slider image</h3>
                <div class="form-group">
                    <label asp-for="Photos">Photo</label>
                    <input asp-for="Photos" class="form-control">
                    <span asp-validation-for="Photos" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sale">Sub title</label>
                    <input asp-for="Sale" class=" form-control">
                    <span asp-validation-for="Sale" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Desc">Description</label>
                    <input asp-for="Desc" class=" form-control">
                    <span asp-validation-for="Desc" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class=" form-control">
                    <span asp-validation-for="Title" class="text-danger my-1"></span>
                </div>

                <button class="btn btn-success">Create</button>
                <a asp-controller="Slider" asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

BackEndProject/Areas/AdminArea/Views/Slider/Index.cshtml
@model IEnumerable<Slider>

@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<div class="container-fluid page-body-wrapper">
    <div class="main-panel">
        <div class="">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Inverse table</h4>
                        <p class="card-description">
                            Add class <code>.table-dark</code>
                        </p>
                        <table class="table table-dark">
                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th> Image </th>
                                    <th> Sale </th>
                                    <th> Title </th>
                                    <th> Desc </th>
                                    <th> Setting </th>

                                </tr>
                            </thead>

                            <tbbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @count </td>
                                        <td><img style="width:70px; height:70px; border-radius:50px;" src="~/assets/img/slider/@item.Image" alt="Slider" /> </td>
                                        <td>@item.Selling</td>
                                        <td>@item.Title</td>
                                        <td>@item.Desc</td>
                                        <td>
                                            <button type="button" class="btn btn-primary">Detail</button>
                                            <a asp-controller="Slider" asp-action="Update" asp-route-id="@item.Id" type="button" class="btn btn-warning">Update</a>
                                            <a asp-controller="Slider" asp-action="Create" class="btn btn-success">Create</a>
                                            <form style="width:15px; height:5px;"  asp-action="Delete" asp-route-id="@item.Id" method="post">
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    count++;

                                }

                            </tbbody>


                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BackEndProject/Areas/AdminArea/Views/Slider/Update.cshtml
@model SliderUpdateVM

@{
    ViewData["Title"] = "Update";
}


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update</h4>
            <form asp-action="Update" method="post" enctype="multipart/form-data">
                <h3>Slider image</h3>
                <div class="form-group">
                    <label asp-for="Photos">Photo</label>
                    <input asp-for="Photos" class="form-control">
                    <span asp-validation-for="Photos" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sale">Sub title</label>
                    <input asp-for="Sale" class=" form-control">
                    <span asp-validation-for="Sale" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Desc">Description</label>
                    <input asp-for="Desc" class=" form-control">
                    <span asp-validation-for="Desc" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class=" form-control">
                    <span asp-validation-for="Title" class="text-danger my-1"></span>
                </div>

                <button class="btn btn-success">Update</button>
                <a asp-controller="Slider" asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>