BackEndProject/Models/Shoes.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Models
{
    public class Shoes : BaseEntity
    {
        public string Image { get; set; }
        public string SubTitle { get; set; }
        public string Title { get; set; }
        [NotMapped]
        public IFormFile Photos { get; set; }
    }
}

BackEndProject/Areas/AdminArea/Controllers/ShoeController.cs
using BackEndProject.Data;
using BackEndProject.Helper;
using BackEndProject.Models;
using BackEndProject.ViewModels.ShoeViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class ShoeController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ShoeController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Shoes> shoes = await _context.Shoes.ToListAsync();
            return View(shoes);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ShoeCreateVM shoeCreate)
        {
            if (!ModelState.IsValid) return View();

            foreach (var photo in shoeCreate.Photos)
            {
                if (!photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photos", "Please choose correct image type");
                    return View();
                }


                if (!photo.CheckFileSize(200))
                {
                    ModelState.AddModelError("Photos", "Please choose correct image size");
                    return View();
                }
            }

            foreach (var photo in shoeCreate.Photos)
            {
                string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;

                string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", fileName);

                await BackEndProject.Helper.Helper.SaveFile(path, photo);

                Shoes newShoe = new Shoes
                {
                    Image = fileName,
                    SubTitle = shoeCreate.SubTitle,
                    Title = shoeCreate.Title
                };

                await _context.Shoes.AddAsync(newShoe);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (id is null) return BadRequest();

            Shoes shoes = await GetByIdAsync(id);

            if (shoes == null) return NotFound();

            ShoeUpdateVM model = new ShoeUpdateVM
            {
                Id = shoes.Id,
                SubTitle = shoes.SubTitle,
                Title = shoes.Title
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, ShoeUpdateVM shoeUpdate)
        {
            if (id is null) return BadRequest();

            if (!ModelState.IsValid) return View(shoeUpdate);

            var dbShoe = await GetByIdAsync((int)id);

            if (dbShoe == null) return NotFound();

            if (shoeUpdate.Photos != null)
            {

                foreach (var photo in shoeUpdate.Photos)
                {
                    if (!photo.CheckFileType("image/"))
                    {
                        ModelState.AddModelError("Photos", "Please choose correct image type");
                        return View(shoeUpdate);
                    }


                    if (!photo.CheckFileSize(500))
                    {
                        ModelState.AddModelError("Photos", "Please choose correct image size");
                        return View(shoeUpdate);
                    }

                }

                foreach (var item in shoeUpdate.Photos)
                {
                    string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", dbShoe.Image);
                    BackEndProject.Helper.Helper.DeleteFile(path);
                }

                foreach (var photo in shoeUpdate.Photos)
                {

                    string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;

                    string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", fileName);

                    await BackEndProject.Helper.Helper.SaveFile(path, photo);

                    dbShoe.Image = fileName;
                }
            }


            dbShoe.SubTitle = shoeUpdate.SubTitle;
            dbShoe.Title = shoeUpdate.Title;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            Shoes shoes = await GetByIdAsync((int)id);

            if (shoes == null) return NotFound();

            string path = BackEndProject.Helper.Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", shoes.Image);

            //if (System.IO.File.Exists(path))
            //{
            //    System.IO.File.Delete(path);
            //}

            BackEndProject.Helper.Helper.DeleteFile(path);

            _context.Shoes.Remove(shoes);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<Shoes> GetByIdAsync(int? id)
        {
            return await _context.Shoes.Where(m => m.Id == id).FirstOrDefaultAsync();
        }

    }
}

BackEndProject/Areas/AdminArea/Views/Shoe/Create.cshtml
@model ShoeCreateVM

@{
    ViewData["Title"] = "Create";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <h3>Shoe image</h3>
                <div class="form-group">
                    <label asp-for="Photos">Photo</label>
                    <input asp-for="Photos" class="form-control">
                    <span asp-validation-for="Photos" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">SubTitle</label>
                    <input asp-for="SubTitle" class=" form-control">
                    <span asp-validation-for="SubTitle" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class=" form-control">
                    <span asp-validation-for="Title" class="text-danger my-1"></span>
                </div>
                <button class="btn btn-success">Create</button>
                <a asp-controller="Shoe" asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

BackEndProject/Areas/AdminArea/Views/Shoe/Index.cshtml
@model IEnumerable<Shoes>

@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<div class="container-fluid page-body-wrapper">
    <div class="main-panel">
        <div class="">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Inverse table</h4>
                        <p class="card-description">
                            Add class <code>.table-dark</code>
                        </p>
                        <table class="table table-dark">
                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th> Image </th>
                                    <th> SubTitle </th>
                                    <th> Title </th>
                                    <th> Setting </th>

                                </tr>
                            </thead>

                            <tbbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @count </td>
                                        <td><img style="width:70px; height:70px; border-radius:50px;" src="~/assets/img/banner/@item.Image" alt="Slider" /> </td>
                                        <td>@item.SubTitle</td>
                                        <td>@Html.Raw(item.Title)</td>
                                        <td>
                                            <button type="button" class="btn btn-primary">Detail</button>
                                            <a asp-controller="Shoe" asp-action="Update" asp-route-id="@item.Id" type="button" class="btn btn-warning">Update</a>
                                            <a asp-controller="Shoe" asp-action="Create" class="btn btn-success">Create</a>
                                            <form style="display : inline-block;" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    count++;

                                }

                            </tbbody>


                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BackEndProject/Areas/AdminArea/Views/Shoe/Update.cshtml
@model ShoeUpdateVM

@{
    ViewData["Title"] = "Update";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update</h4>
            <form asp-action="Update" method="post" enctype="multipart/form-data">
                <h3>Shoe image</h3>
                <div class="form-group">
                    <label asp-for="Photos">Photo</label>
                    <input asp-for="Photos" class="form-control">
                    <span asp-validation-for="Photos" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">Sub title</label>
                    <input asp-for="SubTitle" class=" form-control">
                    <span asp-validation-for="SubTitle" class="text-danger my-1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class=" form-control">
                    <span asp-validation-for="Title" class="text-danger my-1"></span>
                </div>
                <button class="btn btn-success">Update</button>
                <a asp-controller="Shoe" asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>